%-----------------------------------------------------------------------
% Job saved on 11-Aug-2022 00:49:39 by cfg_util (rev $Rev: 7345 $)
% spm SPM - SPM12 (7771)
% cfg_basicio BasicIO - Unknown
%-----------------------------------------------------------------------
matlabbatch{1}.spm.stats.fmri_spec.dir = {'glm'};
matlabbatch{1}.spm.stats.fmri_spec.timing.units = 'secs';
matlabbatch{1}.spm.stats.fmri_spec.timing.RT = TR;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t = nSlices;
matlabbatch{1}.spm.stats.fmri_spec.timing.fmri_t0 = nSlices/2;
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.scans = {
                                                 'nifti/rbold.nii,1'
                                                 'nifti/rbold.nii,2'
                                                 'nifti/rbold.nii,3'
                                                 'nifti/rbold.nii,4'
                                                 'nifti/rbold.nii,5'
                                                 'nifti/rbold.nii,6'
                                                 'nifti/rbold.nii,7'
                                                 'nifti/rbold.nii,8'
                                                 'nifti/rbold.nii,9'
                                                 'nifti/rbold.nii,10'
                                                 'nifti/rbold.nii,11'
                                                 'nifti/rbold.nii,12'
                                                 'nifti/rbold.nii,13'
                                                 'nifti/rbold.nii,14'
                                                 'nifti/rbold.nii,15'
                                                 'nifti/rbold.nii,16'
                                                 'nifti/rbold.nii,17'
                                                 'nifti/rbold.nii,18'
                                                 'nifti/rbold.nii,19'
                                                 'nifti/rbold.nii,20'
                                                 'nifti/rbold.nii,21'
                                                 'nifti/rbold.nii,22'
                                                 'nifti/rbold.nii,23'
                                                 'nifti/rbold.nii,24'
                                                 'nifti/rbold.nii,25'
                                                 'nifti/rbold.nii,26'
                                                 'nifti/rbold.nii,27'
                                                 'nifti/rbold.nii,28'
                                                 'nifti/rbold.nii,29'
                                                 'nifti/rbold.nii,30'
                                                 'nifti/rbold.nii,31'
                                                 'nifti/rbold.nii,32'
                                                 'nifti/rbold.nii,33'
                                                 'nifti/rbold.nii,34'
                                                 'nifti/rbold.nii,35'
                                                 'nifti/rbold.nii,36'
                                                 'nifti/rbold.nii,37'
                                                 'nifti/rbold.nii,38'
                                                 'nifti/rbold.nii,39'
                                                 'nifti/rbold.nii,40'
                                                 'nifti/rbold.nii,41'
                                                 'nifti/rbold.nii,42'
                                                 'nifti/rbold.nii,43'
                                                 'nifti/rbold.nii,44'
                                                 'nifti/rbold.nii,45'
                                                 'nifti/rbold.nii,46'
                                                 'nifti/rbold.nii,47'
                                                 'nifti/rbold.nii,48'
                                                 'nifti/rbold.nii,49'
                                                 'nifti/rbold.nii,50'
                                                 'nifti/rbold.nii,51'
                                                 'nifti/rbold.nii,52'
                                                 'nifti/rbold.nii,53'
                                                 'nifti/rbold.nii,54'
                                                 'nifti/rbold.nii,55'
                                                 'nifti/rbold.nii,56'
                                                 'nifti/rbold.nii,57'
                                                 'nifti/rbold.nii,58'
                                                 'nifti/rbold.nii,59'
                                                 'nifti/rbold.nii,60'
                                                 'nifti/rbold.nii,61'
                                                 'nifti/rbold.nii,62'
                                                 'nifti/rbold.nii,63'
                                                 'nifti/rbold.nii,64'
                                                 'nifti/rbold.nii,65'
                                                 'nifti/rbold.nii,66'
                                                 'nifti/rbold.nii,67'
                                                 'nifti/rbold.nii,68'
                                                 'nifti/rbold.nii,69'
                                                 'nifti/rbold.nii,70'
                                                 'nifti/rbold.nii,71'
                                                 'nifti/rbold.nii,72'
                                                 'nifti/rbold.nii,73'
                                                 'nifti/rbold.nii,74'
                                                 'nifti/rbold.nii,75'
                                                 'nifti/rbold.nii,76'
                                                 'nifti/rbold.nii,77'
                                                 'nifti/rbold.nii,78'
                                                 'nifti/rbold.nii,79'
                                                 'nifti/rbold.nii,80'
                                                 'nifti/rbold.nii,81'
                                                 'nifti/rbold.nii,82'
                                                 'nifti/rbold.nii,83'
                                                 'nifti/rbold.nii,84'
                                                 'nifti/rbold.nii,85'
                                                 'nifti/rbold.nii,86'
                                                 'nifti/rbold.nii,87'
                                                 'nifti/rbold.nii,88'
                                                 'nifti/rbold.nii,89'
                                                 'nifti/rbold.nii,90'
                                                 'nifti/rbold.nii,91'
                                                 'nifti/rbold.nii,92'
                                                 'nifti/rbold.nii,93'
                                                 'nifti/rbold.nii,94'
                                                 'nifti/rbold.nii,95'
                                                 'nifti/rbold.nii,96'
                                                 'nifti/rbold.nii,97'
                                                 'nifti/rbold.nii,98'
                                                 'nifti/rbold.nii,99'
                                                 'nifti/rbold.nii,100'
                                                 'nifti/rbold.nii,101'
                                                 'nifti/rbold.nii,102'
                                                 'nifti/rbold.nii,103'
                                                 'nifti/rbold.nii,104'
                                                 'nifti/rbold.nii,105'
                                                 'nifti/rbold.nii,106'
                                                 'nifti/rbold.nii,107'
                                                 'nifti/rbold.nii,108'
                                                 'nifti/rbold.nii,109'
                                                 'nifti/rbold.nii,110'
                                                 'nifti/rbold.nii,111'
                                                 'nifti/rbold.nii,112'
                                                 'nifti/rbold.nii,113'
                                                 'nifti/rbold.nii,114'
                                                 'nifti/rbold.nii,115'
                                                 'nifti/rbold.nii,116'
                                                 'nifti/rbold.nii,117'
                                                 'nifti/rbold.nii,118'
                                                 'nifti/rbold.nii,119'
                                                 'nifti/rbold.nii,120'
                                                 'nifti/rbold.nii,121'
                                                 'nifti/rbold.nii,122'
                                                 'nifti/rbold.nii,123'
                                                 'nifti/rbold.nii,124'
                                                 'nifti/rbold.nii,125'
                                                 'nifti/rbold.nii,126'
                                                 'nifti/rbold.nii,127'
                                                 'nifti/rbold.nii,128'
                                                 'nifti/rbold.nii,129'
                                                 'nifti/rbold.nii,130'
                                                 'nifti/rbold.nii,131'
                                                 'nifti/rbold.nii,132'
                                                 'nifti/rbold.nii,133'
                                                 'nifti/rbold.nii,134'
                                                 'nifti/rbold.nii,135'
                                                 'nifti/rbold.nii,136'
                                                 'nifti/rbold.nii,137'
                                                 'nifti/rbold.nii,138'
                                                 'nifti/rbold.nii,139'
                                                 'nifti/rbold.nii,140'
                                                 'nifti/rbold.nii,141'
                                                 'nifti/rbold.nii,142'
                                                 'nifti/rbold.nii,143'
                                                 'nifti/rbold.nii,144'
                                                 'nifti/rbold.nii,145'
                                                 'nifti/rbold.nii,146'
                                                 'nifti/rbold.nii,147'
                                                 'nifti/rbold.nii,148'
                                                 'nifti/rbold.nii,149'
                                                 'nifti/rbold.nii,150'
                                                 'nifti/rbold.nii,151'
                                                 'nifti/rbold.nii,152'
                                                 'nifti/rbold.nii,153'
                                                 };
%%
matlabbatch{1}.spm.stats.fmri_spec.sess.cond = struct('name', {}, 'onset', {}, 'duration', {}, 'tmod', {}, 'pmod', {}, 'orth', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi = {''};
matlabbatch{1}.spm.stats.fmri_spec.sess.regress = struct('name', {}, 'val', {});
matlabbatch{1}.spm.stats.fmri_spec.sess.multi_reg = {fullfile(pathSubject,'/physio_out/multiple_regressors.txt')};
matlabbatch{1}.spm.stats.fmri_spec.sess.hpf = 128;
matlabbatch{1}.spm.stats.fmri_spec.fact = struct('name', {}, 'levels', {});
matlabbatch{1}.spm.stats.fmri_spec.bases.hrf.derivs = [0 0];
matlabbatch{1}.spm.stats.fmri_spec.volt = 1;
matlabbatch{1}.spm.stats.fmri_spec.global = 'None';
matlabbatch{1}.spm.stats.fmri_spec.mthresh = 0.8;
matlabbatch{1}.spm.stats.fmri_spec.mask = {''};
matlabbatch{1}.spm.stats.fmri_spec.cvi = 'AR(1)';
matlabbatch{2}.spm.stats.fmri_est.spmmat(1) = cfg_dep('fMRI model specification: SPM.mat File', substruct('.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','spmmat'));
matlabbatch{2}.spm.stats.fmri_est.write_residuals = 0;
matlabbatch{2}.spm.stats.fmri_est.method.Classical = 1;
